name: Snowflake CD Pipeline (PROD - Real Deployment)

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install schemachange

      - name: Create connections.toml file
        run: |
          mkdir -p ~/.snowflake
          echo "[connections]" > ~/.snowflake/connections.toml
          echo "account = \"${{ secrets.SNOWFLAKE_ACCOUNT }}\"" >> ~/.snowflake/connections.toml
          echo "user = \"${{ secrets.SNOWFLAKE_USER }}\"" >> ~/.snowflake/connections.toml
          echo "password = \"${{ secrets.SNOWFLAKE_PASSWORD }}\"" >> ~/.snowflake/connections.toml
          echo "role = \"${{ secrets.SNOWFLAKE_ROLE }}\"" >> ~/.snowflake/connections.toml
          echo "warehouse = \"${{ secrets.SNOWFLAKE_WAREHOUSE }}\"" >> ~/.snowflake/connections.toml
          echo "database = \"${{ secrets.SNOWFLAKE_DATABASE_PROD }}\"" >> ~/.snowflake/connections.toml
          echo "schema = \"${{ secrets.SNOWFLAKE_SCHEMA }}\"" >> ~/.snowflake/connections.toml
          chmod 0600 ~/.snowflake/connections.toml

      - name: Show connections.toml contents (for debug)
        run: |
          cat ~/.snowflake/connections.toml

      - name: Deploy to PROD_DB using schemachange
        run: |
          schemachange \
            -f sql/ \
            --connection-name connections \
            --change-history-table "${{ secrets.SNOWFLAKE_DATABASE_PROD }}.${{ secrets.SNOWFLAKE_SCHEMA }}.CHANGE_HISTORY" \
            --create-change-history-table