name: CD - Snowflake Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install schemachange
        run: pip install schemachange

      - name: Deploy to Snowflake (Prod)
        run: |
          schemachange -f sql/ \
            -a ${{ secrets.SNOWSQL_ACCOUNT }} \
            -u ${{ secrets.SNOWSQL_USER }} \
            -r ${{ secrets.SNOWSQL_ROLE }} \
            -w ${{ secrets.SNOWSQL_WAREHOUSE }} \
            -d ${{ secrets.SNOWSQL_DATABASE_PROD }} \
            -c CHANGE_HISTORY \
            -s ${{ secrets.SNOWSQL_SCHEMA }}
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWSQL_PWD }}
