name: CD - Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Deployment
        run: |
          echo "🚀 Deploying SQL to production..."
          find sql/production -name "*.sql"
          echo "✅ Deployment complete (simulated)"