name: CD - Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-linux_x86_64.zip
          unzip snowsql-linux_x86_64.zip
          ./snowsql-linux_x86_64/install
          export PATH=$PATH:$PWD/snowsql-linux_x86_64

      - name: Deploy SQL to Snowflake Prod DB
        run: |
          ./snowsql-linux_x86_64/snowsql \
            -a ${{ secrets.SNOWSQL_ACCOUNT }} \
            -u ${{ secrets.SNOWSQL_USER }} \
            -r ${{ secrets.SNOWSQL_ROLE }} \
            -w ${{ secrets.SNOWSQL_WAREHOUSE }} \
            -d ${{ secrets.SNOWSQL_DATABASE_PROD }} \
            -s ${{ secrets.SNOWSQL_SCHEMA }} \
            -f .github/workflows/prod_deploy.sql
        env:
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
