name: Snowflake CD Pipeline (Prod)

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install schemachange
        run: pip install schemachange

      - name: Create connections.toml
        run: |
          echo "[connections.default]" > connections.toml
          echo "user = '${{ secrets.SNOWSQL_USER }}'" >> connections.toml
          echo "password = '${{ secrets.SNOWSQL_PWD }}'" >> connections.toml
          echo "account = '${{ secrets.SNOWSQL_ACCOUNT }}'" >> connections.toml
          echo "role = '${{ secrets.SNOWSQL_ROLE }}'" >> connections.toml
          echo "warehouse = '${{ secrets.SNOWSQL_WAREHOUSE }}'" >> connections.toml
          echo "database = '${{ secrets.SNOWSQL_DATABASE_PROD }}'" >> connections.toml
          echo "schema = '${{ secrets.SNOWSQL_SCHEMA }}'" >> connections.toml

      - name: Debug connections.toml (safe)
        run: |
          echo "---- connections.toml ----"
          cat connections.toml | sed 's/password = .*/password = "***"/'
          echo "--------------------------"

      - name: Run schemachange (PROD)
        run: |
          schemachange -f sql --create-change-history-table

          