name: Snowflake MLOps CI/CD

on:
  push:
    branches: [ dev, stage, main ]
  pull_request:
    branches: [ stage, main ]

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

jobs:
  Build:
    name: Build and Train Model
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ml/requirements.txt

      - name: Train model with Snowpark + MLflow
        run: python ml/train_model.py

  DeployDev:
    name: Deploy to Dev
    if: github.ref == 'refs/heads/dev'
    needs: Build
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: http://dev.mymodel.endpoint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload model and deploy UDF
        run: python ml/upload_model.py
      - name: Upload MLflow logs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-logs
          path: mlruns/

  DeployStaging:
    name: Deploy to Staging
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: http://test.mymodel.endpoint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload model and deploy UDF
        run: python ml/upload_model.py
      - name: Upload MLflow logs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-logs
          path: mlruns/

  DeployProd:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Prod
      url: http://prod.mymodel.endpoint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload model and deploy UDF
        run: python ml/upload_model.py
      - name: Upload MLflow logs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-logs
          path: mlruns/
