name: MLOps Pipeline

on:
  push:
    branches:
      - dev
      - stage
      - main

jobs:
  install-train-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Train the Model
        run: |
          python ml/train_model_c.py

      - name: Upload Model to Snowflake Stage
        run: |
          python ml/upload_model.py

  run-ci-tests:
    if: github.ref == 'refs/heads/stage'
    needs: install-train-upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run CI Tests
        run: |
          python tests/test_pipeline.py
